name: Notify to Slack

on: push

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: dev
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_USERNAME: Deploy Robot
      SLACK_ICON_EMOJI: ":robot_face:"
      SLACK_TITLE: ${{ github.repository }}

    steps:
      - name: Deploy Start
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_COLOR: warning
          SLACK_MESSAGE: dev環境へのデプロイを開始します

      - name: Error
        run: exit 1

      - name: Sleep
        run: sleep 30

      - name: Deploy Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_MESSAGE: dev環境へのデプロイが完了しました

      - name: Deploy Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: dev環境へのデプロイが失敗しました
