name: Notify to Slack

on: push

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Notify to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: Deploy Robot
          SLACK_ICON_EMOJI: ":robot_face:"
          SLACK_COLOR: warning
          SLACK_TITLE: ${{ github.repository }}
          SLACK_MESSAGE: dev環境へのデプロイを開始します
